version: '3.7'

services:
  cube_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  cube_web:
    build: .
    command: sh -c "python3 /usr/src/cube/manage.py migrate && python3 /usr/src/cube/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/cube
    ports:
      - "8000:8000"
    depends_on:
      - cube_db
volumes:
  postgres_data: