# Generated by Django 4.1.5 on 2023-06-10 13:09

import cubeapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeapp', '0007_viewcount_viewcount_cubeapp_vie_viewed__28865d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=1, upload_to='video/', validators=[cubeapp.validators.validate_video, cubeapp.validators.validate_file_size], verbose_name='Видеофайл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[cubeapp.validators.validate_image, cubeapp.validators.validate_file_size], verbose_name='Превью'),
        ),
    ]
